# Generated by Django 3.2.7 on 2021-11-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keys', models.CharField(max_length=200)),
                ('dataframe', models.TextField()),
                ('search_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
